### ISSUE TITLE
Loss goes to NaN/INF when using Multilingual BERT

### ISSUE THREAD

**Issue by rohandas14** [jfhetzer/e2e-coref#1]
Hello,

First of all, thank you for your work on the PyTorch implementation of these two papers. I am sure this will be helpful to many folks.

I am trying to use mBERT in place of BERT and evaluating on the English OntoNotes dataset. However the loss goes to NaN in the first batch itself, as seen below.

```
Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
/projects/roda9210/software/anaconda/envs/coref/lib/python3.10/site-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
### Start Training ###
running on: cuda:0 cuda:0
running for: 20 epochs
number of batches: 3368
saving ckpts to: multilingual-bert-base

max_ment_width = 30
genres = [
  "bc"
  "bn"
  "mz"
  "nw"
  "pt"
  "tc"
  "wb"
]
bin_widths = [
  1
  1
  1
  1
  1
  3
  8
  16
  32
  1
]
dropout = 0.3
feature_size = 20
hidden_size = 3000
hidden_depth = 1
max_ment_dist = 250
ment_ratio = 0.4
max_antes = 50
coref_depth = 2
train_data_file = "train.english.jsonlines"
epochs = 20
eval_gold_path = "./data/data/test.english.v4_gold_conll"
eval_data_file = "test.english.jsonlines"
bert = "bert-base-multilingual-cased"
bert_emb_size = 768
segm_size = 128
max_segm_num = 11
lr_bert = 1e-05
lr_task = 0.0002
data_folder = "./data/data/multilingual_bert_base"

No checkpoint found: Start training from scratch

output[0] has infs

Detected inf/nan during batch_number=0
Last 21 forward frames:
abs min  abs max  metadata
                  task_model.slow_antecedent_scorer.0 Linear
0.00e+00 4.00e-02 weight
0.00e+00 0.00e+00 bias
0.00e+00 1.78e+01 input[0]
9.42e-09 5.05e+00 output
                  task_model.slow_antecedent_scorer.1 ReLU
9.42e-09 5.05e+00 input[0]
0.00e+00 4.81e+00 output
                  task_model.slow_antecedent_scorer.2 Dropout
0.00e+00 4.81e+00 input[0]
0.00e+00 6.67e+00 output
                  task_model.slow_antecedent_scorer.3 Linear
1.44e-05 3.98e-02 weight
0.00e+00 0.00e+00 bias
0.00e+00 6.67e+00 input[0]
3.39e-05 2.46e+00 output
                  task_model.slow_antecedent_scorer Scorer
0.00e+00 1.78e+01 input[0]
3.39e-05 2.46e+00 output
                  task_model.attended_gate.0 Linear
0.00e+00 4.00e-02 weight
0.00e+00 0.00e+00 bias
0.00e+00 4.22e+00 input[0]
6.36e-06 3.79e+00 output
                  task_model.attended_gate.1 Sigmoid
6.36e-06 3.79e+00 input[0]
2.20e-02 9.69e-01 output
                  task_model.attended_gate Sequential
0.00e+00 4.22e+00 input[0]
2.20e-02 9.69e-01 output
                  task_model.genre_emb Embedding
1.00e-04 3.70e-02 weight
0.00e+00 0.00e+00 input[0]
1.62e-03 2.32e-02 output
                  task_model.speaker_emb Embedding
1.02e-03 3.66e-02 weight
0.00e+00 1.00e+00 input[0]
1.02e-03 3.66e-02 output
                  task_model.ante_dist_emb Embedding
1.14e-05 3.94e-02 weight
0.00e+00 9.00e+00 input[0]
1.14e-05 3.94e-02 output
                  task_model.seg_dist_emb Embedding
3.25e-05 3.97e-02 weight
0.00e+00 4.00e+00 input[0]
1.10e-04 3.97e-02 output
                  task_model.slow_antecedent_scorer.0 Linear
0.00e+00 4.00e-02 weight
0.00e+00 0.00e+00 bias
0.00e+00 1.44e+01 input[0]
9.61e-10 4.18e+00 output
                  task_model.slow_antecedent_scorer.1 ReLU
9.61e-10 4.18e+00 input[0]
0.00e+00 4.18e+00 output
                  task_model.slow_antecedent_scorer.2 Dropout
0.00e+00 4.18e+00 input[0]
0.00e+00 5.97e+00 output
                  task_model.slow_antecedent_scorer.3 Linear
1.44e-05 3.98e-02 weight
0.00e+00 0.00e+00 bias
0.00e+00 5.97e+00 input[0]
6.53e-06 1.84e+00 output
                  task_model.slow_antecedent_scorer Scorer
0.00e+00 1.44e+01 input[0]
6.53e-06 1.84e+00 output
                  task_model.attended_gate.0 Linear
0.00e+00 4.00e-02 weight
0.00e+00 0.00e+00 bias
0.00e+00 3.83e+00 input[0]
1.49e-07 3.35e+00 output
                  task_model.attended_gate.1 Sigmoid
1.49e-07 3.35e+00 input[0]
3.39e-02 9.60e-01 output
                  task_model.attended_gate Sequential
0.00e+00 3.83e+00 input[0]
3.39e-02 9.60e-01 output
                  task_model ModelTask
3.06e-05 3.97e-02 ment_width_scorer_emb
5.18e-04 3.94e-02 ante_dist_scorer_emb
1.50e-06 4.58e+00 input[0]
1.50e+01 1.24e+02 input[1]
0.00e+00 0.00e+00 input[2]
1.00e+00 4.00e+00 input[3]
5.00e+00 4.69e+02 input[4]
7.00e+00 4.70e+02 input[5]
1.00e+00 9.00e+00 input[6]
1.00e+00 4.79e+02 input[7]
1.00e+00 4.79e+02 input[8]
0.00e+00      inf output[0]
0.00e+00 1.00e+00 output[1]
0.00e+00 1.89e+02 output[2]
1.00e+00 4.78e+02 output[3]
2.00e+00 4.78e+02 output[4]
6.48e-05 1.21e+00 output[5]



Traceback (most recent call last):
  File "/projects/roda9210/coreference/e2e-coref/train.py", line 165, in <module>
    Trainer(args.c, not args.cpu, args.split).train(args.f, args.amp, args.check)
  File "/projects/roda9210/coreference/e2e-coref/train.py", line 84, in train
    scores, labels, _, _, _, _ = model(*batch)
  File "/projects/roda9210/software/anaconda/envs/coref/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/projects/roda9210/coreference/e2e-coref/model/model.py", line 20, in forward
    return self.task_model(bert_embs, *args)
  File "/projects/roda9210/software/anaconda/envs/coref/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1151, in _call_impl
    hook_result = hook(self, input, result)
  File "/projects/roda9210/software/anaconda/envs/coref/lib/python3.10/site-packages/transformers/debug_utils.py", line 280, in forward_hook
    raise ValueError(
ValueError: DebugUnderflowOverflow: inf/nan detected, aborting as there is no point running further. Please scroll up above this traceback to see the activation values prior to this event.

```

I can't possibly think of any reason why this would be happening. Turning off mixed-precision training doesn't help either. I have been able to successfully train and evaluate on the English OntoNotes dataset using BERT, RoBERTa and XLM-R.

Am I missing something here?

**Comment by rohandas14** [comment]
So it seems like there is some numerical instability when we opt for mixed-precision training. Switching to single precision seems to have fixed this issue.
